-- CreateTable
CREATE TABLE `Logger` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `api` VARCHAR(191) NOT NULL,
    `params` VARCHAR(191),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
